import PDFDocument from 'pdfkit'
import User from '../models/User.js'
import ScreeningResult from '../models/ScreeningResult.js'
import DailyCheckIn from '../models/DailyCheckIn.js'

export const generatePDF = async (req, res) => {
	try {
		const userId = req.user.id
		const user = await User.findById(userId).select('-password')
		const screenings = await ScreeningResult.find({ userId }).sort({ createdAt: -1 }).limit(5)
		const checkIns = await DailyCheckIn.find({ userId }).sort({ createdAt: -1 }).limit(14)

		const doc = new PDFDocument({ margin: 50 })

		res.setHeader('Content-Type', 'application/pdf')
		res.setHeader('Content-Disposition', 'attachment; filename=MatriAI-Report.pdf')
		doc.pipe(res)

		// Header
		doc.fontSize(22).font('Helvetica-Bold').text('MatriAI — Health Report', { align: 'center' })
		doc.moveDown(0.5)
		doc.fontSize(10).font('Helvetica').fillColor('#666')
			.text(`Generated on: ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'center' })
		doc.moveDown(1)

		// Divider
		doc.strokeColor('#e0e0e0').lineWidth(1)
			.moveTo(50, doc.y).lineTo(545, doc.y).stroke()
		doc.moveDown(1)

		// User Info
		doc.fontSize(14).font('Helvetica-Bold').fillColor('#333').text('Patient Information')
		doc.moveDown(0.3)
		doc.fontSize(11).font('Helvetica').fillColor('#444')
		doc.text(`Name: ${user.name}`)
		doc.text(`Age: ${user.age || 'N/A'}`)
		doc.text(`Life Stage: ${user.lifeStage || 'N/A'}`)
		if (user.culturalContext) {
			doc.text(`Living Arrangement: ${user.culturalContext.livingArrangement || 'N/A'}`)
			doc.text(`Support System: ${user.culturalContext.supportSystem || 'N/A'}`)
			doc.text(`Work Status: ${user.culturalContext.workStatus || 'N/A'}`)
		}
		doc.moveDown(1)

		// Screening Results
		doc.fontSize(14).font('Helvetica-Bold').fillColor('#333').text('Screening History')
		doc.moveDown(0.3)
		if (screenings.length === 0) {
			doc.fontSize(11).font('Helvetica').text('No screenings recorded yet.')
		} else {
			screenings.forEach((s, i) => {
				doc.fontSize(11).font('Helvetica').fillColor('#444')
				doc.text(`${i + 1}. ${s.type} — Score: ${s.score} / ${s.type === 'EPDS' ? '30' : '12'} — Severity: ${s.severity}`)
				doc.fontSize(9).fillColor('#888')
					.text(`   Date: ${s.createdAt.toLocaleDateString('en-IN')}`)
			})
		}
		doc.moveDown(1)

		// Mood Logs
		doc.fontSize(14).font('Helvetica-Bold').fillColor('#333').text('Recent Mood Logs (Last 14 days)')
		doc.moveDown(0.3)
		if (checkIns.length === 0) {
			doc.fontSize(11).font('Helvetica').text('No check-ins recorded yet.')
		} else {
			checkIns.forEach(c => {
				doc.fontSize(10).font('Helvetica').fillColor('#444')
				const date = c.createdAt.toLocaleDateString('en-IN')
				const symptoms = c.symptoms.length ? c.symptoms.join(', ') : 'None'
				doc.text(`${date} — Mood: ${c.mood}/10 | Sleep: ${c.sleepQuality || 'N/A'} | Symptoms: ${symptoms}`)
			})
		}
		doc.moveDown(1)

		// Summary
		doc.fontSize(14).font('Helvetica-Bold').fillColor('#333').text('Summary')
		doc.moveDown(0.3)
		const avgMood = checkIns.length > 0
			? (checkIns.reduce((s, c) => s + c.mood, 0) / checkIns.length).toFixed(1)
			: 'N/A'
		const latestScreening = screenings[0]
		doc.fontSize(11).font('Helvetica').fillColor('#444')
		doc.text(`Average Mood (last 14 days): ${avgMood}/10`)
		if (latestScreening) {
			doc.text(`Latest Screening: ${latestScreening.type} — ${latestScreening.severity} (score: ${latestScreening.score})`)
		}
		const allSymptoms = [...new Set(checkIns.flatMap(c => c.symptoms))]
		if (allSymptoms.length) {
			doc.text(`Notable Symptoms: ${allSymptoms.join(', ')}`)
		}
		doc.moveDown(1)

		// Footer
		doc.fontSize(8).fillColor('#999').text(
			'This report is auto-generated by MatriAI for informational purposes and to assist conversations with healthcare providers. It is not a medical diagnosis.',
			{ align: 'center' }
		)

		doc.end()
	} catch (error) {
		res.status(500).json({ message: 'Error generating PDF', error: error.message })
	}
}
